// Generated by scripts/generate.py. Do not edit.
export type HTTPValidationError = { "detail"?: Array<ValidationError>; [key: string]: unknown };
export type ResponseModel = { "code"?: number; "msg"?: string; "data"?: unknown | null; [key: string]: unknown };
export type SmsBulkSendIn = { "recipients": Array<string>; "body": string; "sender_name": string; "name"?: string | null; [key: string]: unknown };
export type SmsOptOutIn = { "phones": Array<string>; "reason"?: string | null; "source"?: "manual" | "import" | "reply"; [key: string]: unknown };
export type SmsSendIn = { "test_mode"?: boolean; "to": string; "body": string; "sender_name": string; [key: string]: unknown };
export type ValidationError = { "loc": Array<string | number>; "msg": string; "type": string; [key: string]: unknown };
export type SmsMessageOut = { "x_id": string; "to": string; "body": string; "sender_name": string; "country_code": string; "encoding": string; "segments": number; "unit_price": number; "cost": number; "status": string; "error"?: string | null; "refunded"?: boolean; "batch_x_id"?: string | null; "source": string; "created_time": string; "sent_at"?: string | null; "delivered_at"?: string | null; "unit": "point"; [key: string]: unknown };
export type SmsBatchOut = { "x_id": string; "name": string; "body": string; "sender_name": string; "source": string; "status": string; "total_recipients": number; "sent_count": number; "failed_count": number; "amount_reserved": number; "amount_refunded": number; "created_time": string; "completed_at"?: string | null; "unit": "point"; [key: string]: unknown };
export type SmsBulkSendOut = { "batch": SmsBatchOut; "invalid_recipients"?: Array<string>; [key: string]: unknown };
export type WalletOut = { "currency": string; "balance": number; "total_topped_up": number; "total_spent": number; "display_currency"?: string | null; "low_balance_threshold"?: number | null; "unit": "point"; [key: string]: unknown };
