"""Generate typed resources from the exported public API contract."""
import json
import keyword
import re
from collections import defaultdict
from pathlib import Path
root = Path(__file__).resolve().parents[1]
spec = json.loads((root / 'openapi.json').read_text())
schemas = spec['components']['schemas']
def ref(s): return s['$ref'].rsplit('/',1)[1]
def ts(s):
    if '$ref' in s: return ref(s)
    if 'const' in s: return json.dumps(s['const'])
    if 'enum' in s: return ' | '.join(json.dumps(v) for v in s['enum'])
    if 'anyOf' in s: return ' | '.join(ts(v) for v in s['anyOf'])
    t = s.get('type')
    if t == 'array': return f'Array<{ts(s.get("items",{}))}>'
    if t == 'object' or 'properties' in s:
        fields = [json.dumps(k) + ('' if k in s.get('required',[]) else '?') + ': ' + ts(v) for k,v in s.get('properties',{}).items()]
        if s.get('additionalProperties',True): fields.append('[key: string]: unknown')
        return '{ ' + '; '.join(fields) + ' }'
    return {'integer':'number','number':'number','string':'string','boolean':'boolean','null':'null'}.get(t,'unknown')
def py(s):
    if '$ref' in s: return repr(ref(s))
    if 'const' in s: return f'Literal[{s["const"]!r}]'
    if 'enum' in s: return 'Literal[' + ', '.join(repr(v) for v in s['enum']) + ']'
    if 'anyOf' in s: return 'Union[' + ', '.join(py(v) for v in s['anyOf']) + ']'
    t=s.get('type')
    if t=='array': return f'List[{py(s.get("items",{}))}]'
    return {'integer':'int','number':'float','string':'str','boolean':'bool','null':'None','object':'Dict[str, Any]'}.get(t,'Any')
def camel(s): return re.sub(r'_([a-z])',lambda m:m[1].upper(),s)
ts_types='// Generated by scripts/generate.py. Do not edit.\n'+ '\n'.join(f'export type {n} = {ts(s)};' for n,s in schemas.items())+'\n'
py_types='"""Generated public API types."""\nfrom typing import Any, Dict, List, Literal, Union, TypedDict, Required, NotRequired\n\n'
for name,schema in schemas.items():
    if schema.get('type')=='object' and schema.get('properties'):
        fields=', '.join(f'{k!r}: '+('Required' if k in schema.get('required',[]) else 'NotRequired')+f'[{py(v)}]' for k,v in schema.get('properties',{}).items())
        py_types+=f'{name} = TypedDict({name!r}, {{{fields}}})\n'
    else: py_types+=f'{name} = {py(schema)}\n'
groups=defaultdict(list)
alias={'get_balance':'balance','client_sms_list_senders':'senders','send_sms':'send','send_bulk':'send_bulk','get_status':'status','client_sms_add_opt_outs':'opt_outs'}
for path,methods in spec['paths'].items():
    group = path.split('/')[2] if path.startswith('/{instance_id}') else 'sms'
    for method,op in methods.items():
        if method not in {'get','post','put','patch','delete'}: continue
        name=alias.get(op['x-sdk-method'],op['x-sdk-method'])
        if keyword.iskeyword(name): name += '_'
        params=[p for p in op.get('parameters',[]) if p['in'] in ('path','query') and p['name']!='instance_id']
        body=op.get('requestBody',{}).get('content',{}).get('application/json',{}).get('schema')
        output=op.get('responses',{}).get('200',{}).get('content',{}).get('application/json',{}).get('schema',{})
        if group=='sms': output={'$ref':'#/components/schemas/'+{'send':'SmsMessageOut','status':'SmsMessageOut','send_bulk':'SmsBulkSendOut','balance':'WalletOut'}.get(name,'')} if name in {'send','status','send_bulk','balance'} else {'type':'object'}
        groups[group].append(dict(name=name,method=method.upper(),path=path,params=params,body=body,output=output,summary=op.get('summary',name)))
ts_resources='// Generated.\nimport type * as T from "./types.js";\n'
def typed_ts(s):
    v=ts(s)
    for name in sorted(schemas,key=len,reverse=True): v=re.sub(r'(?<![\w.])'+re.escape(name)+r'\b','T.'+name,v)
    return v
manifest={}
for group,ops in groups.items():
    title=group.capitalize()+'API'; ts_resources+=f'export interface {title} {{\n'
    manifest[group]={}
    for op in ops:
        fields=[f'{p["name"]}'+('' if p.get('required') else '?')+': '+typed_ts(p.get('schema',{})) for p in op['params']]
        args=[]
        if op['body']: args.append('body: '+typed_ts(op['body']))
        if fields: args.append('params'+('' if any(p.get('required') for p in op['params']) else '?')+': { '+ '; '.join(fields)+' }')
        jsname=camel(op['name']);ts_resources+=f'  /** {op["summary"]} */\n  {jsname}({", ".join(args)}): Promise<{typed_ts(op["output"])}>;\n'
        manifest[group][jsname]={k:op[k] for k in ('method','path')}
        manifest[group][jsname].update(body=bool(op['body']),params=[{'name':p['name'],'in':p['in']} for p in op['params']],unwrap=group=='sms')
    ts_resources+='}\n'
ts_resources+='export interface WhatsAppAPI {\n'+''.join(f'  {g}: {g.capitalize()}API;\n' for g in groups if g!='sms')+'}\n'
ts_resources+='export const operations = '+json.dumps(manifest,indent=2)+' as const;\n'
py_resources='"""Generated resource methods."""\nfrom __future__ import annotations\nfrom typing import Any, Dict, List, Literal, Union\nfrom ._transport import segment\nfrom .types import *\n\n'
for async_ in (False,True):
    prefix='Async' if async_ else ''
    for group,ops in groups.items():
        title=prefix+group.capitalize()+'API';py_resources+=f'class {title}:\n    def __init__(self, client, instance_id=None):\n        self._client = client\n        self._instance_id = instance_id\n\n'
        for op in ops:
            args=[]
            if op['body']: args.append('body: '+py(op['body']))
            for p in op['params']: args.append(p['name']+': '+py(p.get('schema',{}))+('' if p.get('required') else ' = None'))
            path=op['path']
            for param in re.findall(r'\{(\w+)\}',path): path=path.replace('{'+param+'}', '{segment('+('self._instance_id' if param=='instance_id' else param)+')}')
            query='{'+', '.join(repr(p['name'])+': '+p['name'] for p in op['params'] if p['in']=='query')+'}'
            signature='self'+(', *, '+', '.join(args) if args else '')
            py_resources+=f'    {"async " if async_ else ""}def {op["name"]}({signature}) -> {py(op["output"])}:\n        """{op["summary"]}."""\n        return {"await " if async_ else ""}self._client.request({op["method"]!r}, f\'{path}\', body={"body" if op["body"] else "None"}, query={query}, unwrap={group=="sms"})\n\n'
    py_resources+=f'class {prefix}WhatsAppAPI:\n    def __init__(self, client, instance_id):\n'
    for group in groups:
        if group!='sms': py_resources+=f'        self.{group} = {prefix}{group.capitalize()}API(client, instance_id)\n'
    py_resources+='\n'
(root/'typescript/src/types.ts').write_text(ts_types)
(root/'typescript/src/resources.ts').write_text(ts_resources)
(root/'python/src/weezy/types.py').write_text(py_types)
(root/'python/src/weezy/resources.py').write_text(py_resources.rstrip() + '\n')
print('Generated',sum(map(len,groups.values())),'operations in both SDKs')

reference = "# Public API methods\n\nGenerated from the backend routes. Base URL: `https://api.weezy.app/client/api/v1`.\n\n"
for group, ops in groups.items():
    reference += f"## {group}\n\n| JavaScript / TypeScript | Python | HTTP | Route |\n| --- | --- | --- | --- |\n"
    for op in ops:
        prefix = "sms" if group == "sms" else f"whatsapp(instanceId).{group}"
        pyprefix = "sms" if group == "sms" else f"whatsapp(instance_id).{group}"
        reference += f"| `{prefix}.{camel(op['name'])}` | `{pyprefix}.{op['name']}` | {op['method']} | `{op['path']}` |\n"
    reference += "\n"
for target in (root / "API.md", root / "typescript/API.md", root / "python/API.md"):
    target.write_text(reference.rstrip() + '\n')
